"""
LANGGRAPH MULTI-AGENT SYSTEMS
==============================
Multiple specialized AI agents working together to solve complex tasks.

Why multi-agent?
  - One LLM trying to do everything = overwhelmed, makes mistakes.
  - Specialized agents = each expert at one thing = better results.
  - Like a dev team: PM, Frontend Dev, Backend Dev, QA — each has a role.

Two main patterns:
  1. Supervisor → Workers (one boss delegates to specialists)
  2. Graph of Agents (agents hand off to each other directly)

Install: pip install langgraph langchain-anthropic python-dotenv
"""

import os
from dotenv import load_dotenv
load_dotenv()

from typing import TypedDict, Annotated, Literal
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import create_react_agent, ToolNode, tools_condition
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_core.tools import tool
from langchain_core.output_parsers import StrOutputParser

llm = ChatAnthropic(model="claude-sonnet-4-6", temperature=0)

# ─────────────────────────────────────────
# KEY TERMS
# ─────────────────────────────────────────
"""
Supervisor Agent
  - The "manager" LLM. Reads the task, decides which worker to call.
  - Receives worker results, decides what to do next.
  - Routes: task → worker_A → worker_B → ... → FINISH

Worker Agent
  - A specialized agent that does ONE thing well.
  - Examples: researcher, coder, writer, reviewer, data_analyst.
  - Has specific tools and a focused system prompt.

Handoff
  - When one agent passes control to another.
  - The current agent's output becomes the next agent's input.

Command
  - LangGraph's way for an agent to say "go to this node next".
  - from langgraph.types import Command
  - return Command(goto="next_node", update={state_updates})

Subgraph
  - A complete graph used as a node inside a larger graph.
  - Each subgraph has its own state.
  - Like a React component used inside another component.
"""

# ─────────────────────────────────────────
# PATTERN 1: SUPERVISOR → WORKERS
# ─────────────────────────────────────────

# --- Worker Tools ---
@tool
def web_search(query: str) -> str:
    """Search the web for information."""
    return f"Web search results for '{query}': Comprehensive information found about {query}."

@tool
def write_code(description: str, language: str = "python") -> str:
    """Write code based on a description."""
    return f"```{language}\n# Code for: {description}\ndef solution():\n    pass  # Implementation here\n```"

@tool
def analyze_data(data: str, analysis_type: str) -> str:
    """Analyze data and provide insights."""
    return f"Analysis of '{data}' using {analysis_type}: Key insights found."

@tool
def write_report(title: str, content: str) -> str:
    """Write a structured report."""
    return f"# {title}\n\n{content}\n\n*Report generated by AI*"


# --- Specialized Worker Agents ---
research_agent = create_react_agent(
    model=llm,
    tools=[web_search],
    state_modifier="You are a research specialist. Search for accurate, comprehensive information."
)

coding_agent = create_react_agent(
    model=llm,
    tools=[write_code],
    state_modifier="You are an expert programmer. Write clean, efficient, well-documented code."
)

writing_agent = create_react_agent(
    model=llm,
    tools=[write_report],
    state_modifier="You are a technical writer. Write clear, professional reports and documents."
)


# --- Supervisor State ---
class SupervisorState(TypedDict):
    messages: Annotated[list, add_messages]
    next_agent: str  # which worker to call next

WORKERS = ["researcher", "coder", "writer"]

def supervisor_node(state: SupervisorState) -> dict:
    """Supervisor decides which worker to call next."""
    from pydantic import BaseModel, Field

    class SupervisorDecision(BaseModel):
        next: Literal["researcher", "coder", "writer", "FINISH"] = Field(
            description="Which agent to call next, or FINISH if task is complete"
        )
        reasoning: str = Field(description="Why you chose this agent")

    supervisor_llm = llm.with_structured_output(SupervisorDecision)

    supervisor_prompt = f"""You are a supervisor managing a team of AI workers.
Given the conversation, decide who should act next.

Workers available:
- researcher: searches for information and facts
- coder: writes and explains code
- writer: creates reports and documents

Conversation so far:
{[m.content[:200] for m in state['messages'][-5:]]}

Decide: which worker should act next, or say FINISH if the task is complete."""

    decision = supervisor_llm.invoke(supervisor_prompt)
    return {"next_agent": decision.next}

def route_supervisor(state: SupervisorState) -> str:
    """Route to the next worker or end."""
    return state["next_agent"]

def run_researcher(state: SupervisorState) -> dict:
    """Run the research agent."""
    last_human_msg = next(
        m for m in reversed(state["messages"])
        if isinstance(m, HumanMessage)
    )
    result = research_agent.invoke({"messages": [last_human_msg]})
    final_response = result["messages"][-1]
    return {"messages": [AIMessage(content=f"[RESEARCHER]: {final_response.content}")]}

def run_coder(state: SupervisorState) -> dict:
    """Run the coding agent."""
    last_human_msg = next(
        m for m in reversed(state["messages"])
        if isinstance(m, HumanMessage)
    )
    result = coding_agent.invoke({"messages": [last_human_msg]})
    final_response = result["messages"][-1]
    return {"messages": [AIMessage(content=f"[CODER]: {final_response.content}")]}

def run_writer(state: SupervisorState) -> dict:
    """Run the writing agent."""
    context = "\n".join([m.content for m in state["messages"] if isinstance(m, AIMessage)])
    result = writing_agent.invoke({
        "messages": [HumanMessage(content=f"Write a report based on this research:\n{context}")]
    })
    final_response = result["messages"][-1]
    return {"messages": [AIMessage(content=f"[WRITER]: {final_response.content}")]}


# --- Build Supervisor Graph ---
supervisor_graph = StateGraph(SupervisorState)

supervisor_graph.add_node("supervisor", supervisor_node)
supervisor_graph.add_node("researcher", run_researcher)
supervisor_graph.add_node("coder", run_coder)
supervisor_graph.add_node("writer", run_writer)

supervisor_graph.add_edge(START, "supervisor")

# After supervisor decides, route to appropriate worker
supervisor_graph.add_conditional_edges(
    "supervisor",
    route_supervisor,
    {
        "researcher": "researcher",
        "coder": "coder",
        "writer": "writer",
        "FINISH": END,
    }
)

# After each worker, go back to supervisor
for worker in ["researcher", "coder", "writer"]:
    supervisor_graph.add_edge(worker, "supervisor")

supervisor_app = supervisor_graph.compile()

# Run the multi-agent system
task = "Research what LangGraph is, then write a brief report about it"
result = supervisor_app.invoke({
    "messages": [HumanMessage(content=task)],
    "next_agent": ""
})

print("=== MULTI-AGENT RESULT ===")
for msg in result["messages"]:
    if isinstance(msg, AIMessage):
        print(msg.content[:300])
        print()


# ─────────────────────────────────────────
# PATTERN 2: PIPELINE — Agents Pass Work to Each Other
# ─────────────────────────────────────────
"""
Linear pipeline: each agent does its work and passes to the next.
Like an assembly line: research → draft → review → publish.
"""

class PipelineState(TypedDict):
    topic: str
    research: str
    draft: str
    review_feedback: str
    final_article: str

def research_phase(state: PipelineState) -> dict:
    """Phase 1: Research the topic."""
    response = llm.invoke(
        f"Research and summarize key facts about: {state['topic']}"
    )
    return {"research": response.content}

def drafting_phase(state: PipelineState) -> dict:
    """Phase 2: Write article draft from research."""
    response = llm.invoke(
        f"Write a 200-word article about '{state['topic']}' using this research:\n{state['research']}"
    )
    return {"draft": response.content}

def review_phase(state: PipelineState) -> dict:
    """Phase 3: Review the draft."""
    response = llm.invoke(
        f"Review this article and give specific improvement suggestions:\n{state['draft']}"
    )
    return {"review_feedback": response.content}

def revision_phase(state: PipelineState) -> dict:
    """Phase 4: Final revision based on review."""
    response = llm.invoke(
        f"""Revise this article based on the feedback:
Article: {state['draft']}
Feedback: {state['review_feedback']}
Write the improved final version:"""
    )
    return {"final_article": response.content}

pipeline_graph = StateGraph(PipelineState)
pipeline_graph.add_node("research", research_phase)
pipeline_graph.add_node("drafting", drafting_phase)
pipeline_graph.add_node("review", review_phase)
pipeline_graph.add_node("revision", revision_phase)

pipeline_graph.add_edge(START, "research")
pipeline_graph.add_edge("research", "drafting")
pipeline_graph.add_edge("drafting", "review")
pipeline_graph.add_edge("review", "revision")
pipeline_graph.add_edge("revision", END)

pipeline_app = pipeline_graph.compile()

# Stream to see each phase
print("\n=== PIPELINE MULTI-AGENT ===")
for step in pipeline_app.stream({"topic": "LangGraph for AI engineers", "research": "", "draft": "", "review_feedback": "", "final_article": ""}):
    node = list(step.keys())[0]
    print(f"\n✓ {node.upper()} PHASE COMPLETE")

final = pipeline_app.invoke({"topic": "Why Python dominates AI", "research": "", "draft": "", "review_feedback": "", "final_article": ""})
print("\nFINAL ARTICLE:")
print(final["final_article"])


# ─────────────────────────────────────────
# PATTERN 3: PARALLEL AGENTS — Run Multiple Agents at Once
# ─────────────────────────────────────────
"""
Run multiple agents simultaneously, then combine their results.
Like Promise.all() — all run at the same time, wait for all to finish.
"""

class ParallelState(TypedDict):
    topic: str
    technical_analysis: str
    market_analysis: str
    risk_analysis: str
    combined_report: str

def technical_agent_node(state: ParallelState) -> dict:
    response = llm.invoke(
        f"Provide a technical analysis of: {state['topic']}. Focus on implementation, architecture."
    )
    return {"technical_analysis": response.content}

def market_agent_node(state: ParallelState) -> dict:
    response = llm.invoke(
        f"Provide a market analysis of: {state['topic']}. Focus on business value, competition."
    )
    return {"market_analysis": response.content}

def risk_agent_node(state: ParallelState) -> dict:
    response = llm.invoke(
        f"Provide a risk analysis of: {state['topic']}. Focus on challenges, limitations."
    )
    return {"risk_analysis": response.content}

def combine_reports(state: ParallelState) -> dict:
    """Combine all analyses into one report."""
    combined = f"""# Comprehensive Analysis: {state['topic']}

## Technical Analysis
{state['technical_analysis']}

## Market Analysis
{state['market_analysis']}

## Risk Analysis
{state['risk_analysis']}
"""
    return {"combined_report": combined}

parallel_graph = StateGraph(ParallelState)

# Add all nodes
parallel_graph.add_node("technical", technical_agent_node)
parallel_graph.add_node("market", market_agent_node)
parallel_graph.add_node("risk", risk_agent_node)
parallel_graph.add_node("combine", combine_reports)

# Fan out: START → all three agents at once
parallel_graph.add_edge(START, "technical")
parallel_graph.add_edge(START, "market")
parallel_graph.add_edge(START, "risk")

# Fan in: all three → combine
parallel_graph.add_edge("technical", "combine")
parallel_graph.add_edge("market", "combine")
parallel_graph.add_edge("risk", "combine")
parallel_graph.add_edge("combine", END)

parallel_app = parallel_graph.compile()

result = parallel_app.invoke({
    "topic": "Adopting LangGraph in enterprise AI systems",
    "technical_analysis": "",
    "market_analysis": "",
    "risk_analysis": "",
    "combined_report": ""
})

print("\n=== PARALLEL MULTI-AGENT ===")
print(result["combined_report"][:500])


# ─────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────
"""
Multi-Agent Patterns:

1. Supervisor → Workers
   - Supervisor reads task, delegates to specialist workers
   - Workers complete tasks, return to supervisor
   - Supervisor decides when to finish
   Best for: complex tasks needing different expertise

2. Pipeline (Sequential)
   - Research → Draft → Review → Publish
   - Each agent does one phase, hands off to next
   Best for: content creation, data processing workflows

3. Parallel
   - Multiple agents run simultaneously
   - Results combined by a final node
   Best for: analysis from multiple perspectives, batch processing

Key insight:
  "Multi-agent" = multiple calls to LLMs with different system prompts + tools
  Each agent is just: specialized system prompt + relevant tools

Next: Human-in-the-Loop — pause the graph and wait for human approval
"""
